# Generated by Django 2.0.3 on 2018-03-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('experience', models.FloatField(default=0.0)),
                ('work_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.FloatField(default=0.0)),
                ('payment_summ', models.FloatField(default=0.0)),
                ('ndfl_tax', models.FloatField(default=0.0)),
                ('fss_contribution', models.FloatField(default=0.0)),
                ('ops_contribution', models.FloatField(default=0.0)),
                ('foms_contribution', models.FloatField(default=0.0)),
                ('premium', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_summ', models.FloatField(default=0.0)),
                ('ndfl_tax', models.FloatField(default=0.0)),
                ('fss_contribution', models.FloatField(default=0.0)),
                ('ops_contribution', models.FloatField(default=0.0)),
                ('foms_contribution', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='paymentreport',
            name='payment_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.PaymentStatement'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Position'),
        ),
    ]
