# Generated by Django 2.0.3 on 2018-03-19 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_paymentstatement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 22, 47, 38, 432112)),
        ),
    ]
